name: Spell Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cspell:
    name: CSpell
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run cspell
      uses: streetsidesoftware/cspell-action@v7
